import { RouteInfo } from './sidebar.metadata';

export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: '-- Menú',
    moduleName: '',
    icon: '',
    class: 'header',
    groupTitle: true,
    submenu: [],
    roles: ['all'],
  },
  {
    path: '/app/home',
    title: 'Inicio',
    moduleName: 'main',
    icon: 'menu-icon ti-home',
    class: '',
    groupTitle: false,
    submenu: [],
    roles: ['all'],
  },
  {
    path: '/app/devices',
    title: 'Mis Dispositivos',
    moduleName: 'devices',
    icon: 'menu-icon ti-settings',
    class: '',
    groupTitle: false,
    submenu: [],
    roles: ['all']
  },
  {
    path: '/app/account',
    title: 'Mi Cuenta',
    moduleName: 'account',
    icon: 'menu-icon ti-user',
    class: '',
    groupTitle: false,
    submenu: [],
    roles: ['all']
  },
  {
    path: '',
    title: '-- Admin',
    moduleName: '',
    icon: '',
    class: 'header',
    groupTitle: true,
    submenu: [],
    roles: ['admin'],
  },
  {
    path: '',
    title: 'Usuarios',
    moduleName: 'users',
    icon: 'menu-icon icon-people',
    class: 'menu-toggle',
    groupTitle: false,
    submenu: [
      {
        path: '/app/admin/users/list',
        title: 'Lista',
        moduleName: 'users',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        submenu: [],
        roles: ['admin'],
      },
      {
        path: '/app/admin/users/roles',
        title: 'Roles',
        moduleName: 'users',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        submenu: [],
        roles: ['admin'],
      },
      {
        path: '/app/admin/users/sessions',
        title: 'Sesiones',
        moduleName: 'users',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        submenu: [],
        roles: ['admin'],
      },
    ],
    roles: ['admin'],
  },
  {
    path: '',
    title: 'Dispositivos',
    moduleName: 'devices',
    icon: 'menu-icon icon-bulb',
    class: 'menu-toggle',
    groupTitle: false,
    submenu: [
      {
        path: '/app/admin/devices/list',
        title: 'Lista',
        moduleName: 'devices',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        submenu: [],
        roles: ['admin'],
      },
      {
        path: '/app/admin/devices/types',
        title: 'Tipos',
        moduleName: 'devices',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        submenu: [],
        roles: ['admin'],
      },
      {
        path: '',
        title: 'MQTT',
        moduleName: 'mqtt',
        icon: '',
        class: 'ml-sub-menu',
        groupTitle: false,
        submenu: [
          {
            path: '/app/admin/devices/mqtt/users',
            title: 'Usuarios',
            moduleName: 'mqtt',
            icon: '',
            class: 'ml-sub-sub-menu',
            groupTitle: false,
            submenu: [],
            roles: ['admin'],
          },
          {
            path: '/app/admin/devices/mqtt/acl',
            title: 'ACL',
            moduleName: 'mqtt',
            icon: '',
            class: 'ml-sub-sub-menu',
            groupTitle: false,
            submenu: [],
            roles: ['admin'],
          }
        ],
        roles: ['admin'],
      },
    ],
    roles: ['admin'],
  },
  {
    path: '/app/admin/fota',
    title: 'FOTA',
    moduleName: 'fota',
    icon: 'menu-icon icon-cloud-download',
    class: '',
    groupTitle: false,
    submenu: [],
    roles: ['admin']
  },
  {
    path: '/auth/signin',
    title: 'Cerrar Sesión',
    moduleName: 'logout',
    icon: 'menu-icon ti-power-off',
    class: '',
    groupTitle: false,
    submenu: [],
    roles: ['all']
  },
];
